[package]
org = "ballerina"
name = "jsonutils"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../jsonutils-native/build/libs/jsonutils-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "jsonutils"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../jsonutils-test-utils/build/libs/jsonutils-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.jsonutils"
artifactId = "jsonutils"
version = "@project.version@"
scope = "testOnly"

